name: main
on: push

jobs:
  build-and-deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/setup-sam@v1
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: sam build
      working-directory: cloud-resume
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      working-directory: cloud-resume