name: main
on: push

jobs:
  build-and-deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/setup-sam@v1
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9.x"
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: sam build
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
  
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
      - uses: chetan/invalidate-cloudfront-action@v2
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: www.roddyezell.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          SOURCE_DIR: ./resume-site
  
  invalidate-cloudfront:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"